### ISSUE TITLE
Switch to mdb files instead of local SQL server

### ISSUE THREAD

**Issue by Phyyl** [dragonmost/PlebQuest-2.0#2]

**Comment by Phyyl** [comment]
why close bakéé

**Comment by dragonmost** [comment]
cuz i no care. cest pas ca le but du project

**Comment by Phyyl** [comment]
mais ca permetterait de faire un serveur local sans setup mysql..

**Comment by dragonmost** [comment]
no clue how they work cest mic qui soccupe de la BD si y veut les faire sure.
